### ISSUE TITLE
Suggestion to fork or maintain an existing project. 

### ISSUE THREAD

**Issue by Lucky-069** [sixf0ur/SnapPass#1]
I'm sure you must be aware of snapmod by rodit. The project works very well and has every feature needed, it hasn't been updated in a while. It would be great if you could maintain it or create a fork and just do base updates!

**Comment by sixf0ur** [comment]
i'll take a look at the community

**Comment by Lucky-069** [comment]
Hey mate, reopening this issue to check if you managed to look at the [Snapmod](https://github.com/rodit/SnapMod). This is such a good project that's dying. Another dev tried maintaining a fork but he's unable to do so,please look into this, I feel for some reason you can do it effectively. The fork I was talking about is [SnapMod-new](https://github.com/RevealedSoulEven/SnapMod-new)

**Comment by Lucky-069** [comment]
@sixf0ur Look into this
